In [ ]:
!pip install xgboost

In [ ]:
import pandas as pd
import numpy as np
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
import warnings
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, StackingClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler
import warnings

warnings.filterwarnings("ignore")
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import matthews_corrcoef




warnings.filterwarnings("ignore")

warnings.filterwarnings("ignore")
from scipy.stats import ttest_ind
from google.colab import files
from google.colab import drive

import warnings

warnings.filterwarnings("ignore")
import os

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
csv_file_path_main = '/content/drive/My Drive/Academic_Thesis/Final_Thesis/DEG_CSVs/ML_DEG_dataset.csv'

train_main = pd.read_csv(csv_file_path_main)

In [ ]:
train_main.head()

geo_accession  target       TUBB       CDT1        LPP      UGP2       MFN2  \
0     GSM277495       0  1971.4430   35.27089   8473.877  61.36008   878.7402   
1     GSM277496       1   606.7773  468.34940   5391.271  30.43565   715.1648   
2     GSM277497       0  8916.9360   82.57671  27863.030  34.52829  1160.9170   
3     GSM277498       1  3148.3370  580.13820   5325.731  36.86857   470.3635   
4     GSM277499       0  3906.8750   93.08880  20692.270  64.22387  1166.8960   

   HIST1H2BD     SEMA3E       RGS5  ...       LCAT      MCM5       ASPM  \
0  3212.8910 -16.952740   403.8409  ...   79.59111  224.2105   144.5214   
1   323.2217  -8.576768   615.3448  ...   94.12312  361.0414  1086.0480   
2   778.4032  52.338870  1263.4070  ...  217.14050  288.5819   352.1789   
3   328.6313 -10.858900   124.0610  ...   47.98767  555.0460  1424.9820   
4  1181.2000  -0.608158   734.8578  ...  214.11700  189.5398   141.4275   

        HMGCS2       AGT     CCDC68      CD46      PLCG2       SOX4     NUP107  
0  18967.55000  143.8013  624.58200  2115.487  1365.6700   426.4089   419.1906  
1     96.36639  235.3114   58.14994  5566.119   303.0632  1563.1800  1017.3650  
2  11035.48000  115.9880  126.39290  1498.417   810.1133   590.7308   619.0782  
3  14479.59000  152.0744  172.29320  3903.002   181.3151  1438.3140  1847.4700  
4  31952.92000  154.1114  201.99280  2057.749   543.7367   535.5609   462.7539  

[5 rows x 1473 columns]

In [ ]:
csv_file_path_test1 = '/content/drive/My Drive/Academic_Thesis/Final_Thesis/ThesisAllData/GSE106582_gene_expression_renamed.csv'
df_test1 = pd.read_csv(csv_file_path_test1)

In [ ]:
df_test1.shape

(194, 47292)

In [ ]:
csv_file_path_test2 = '/content/drive/My Drive/Academic_Thesis/Final_Thesis/ThesisAllData/GSE21815_gene_expression_renamed.csv'
df_test2 = pd.read_csv(csv_file_path_test2)

df_test2.shape

(141, 41002)

In [ ]:
csv_file_path_test3 = '/content/drive/My Drive/Academic_Thesis/Final_Thesis/ThesisAllData/GSE8671_gene_expression_renamed.csv'
df_test3 = pd.read_csv(csv_file_path_test3)

df_test3.shape

(64, 54615)

In [ ]:
csv_file_path_test4 = '/content/drive/My Drive/Academic_Thesis/Final_Thesis/ThesisAllData/GSE44076_gene_expression_renamed.csv'
df_test4 = pd.read_csv(csv_file_path_test4)

df_test4.shape

(148, 49295)

# From 10 top genes

## 1st Dataset [GSE106582]

In [ ]:
df_train= train_main

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','target']

df_train = train_main
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE106582_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE106582_gene_expression_renamed.csv")
df_test= df_test1
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 93.63%
LR Testing Accuracy: 96.91%
Precision: 0.97, Recall: 0.97, F1-Score: 0.97, MCC: 0.94
LR Testing Accuracy: 96.91%
Confusion Matrix:
[[114   3]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.96      0.96      0.96        77

    accuracy                           0.97       194
   macro avg       0.97      0.97      0.97       194
weighted avg       0.97      0.97      0.97       194

------------------------------------------------------------
KNN Training Accuracy: 93.61%
KNN Testing Accuracy: 96.39%
Precision: 0.96, Recall: 0.96, F1-Score: 0.96, MCC: 0.92
KNN Testing Accuracy: 96.39%
Confusion Matrix:
[[113   4]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.95      0.96      0.95        77

    accuracy                     

##20 Hub Genes

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','DPYSL3','TIMP2',
                       'PRNP', 'SPARCL1', 'SNCA', 'CSRP1', 'ILK', 'MEF2C', 'PALLD', 'CAV2','target']


df_train = train_main
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE106582_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE106582_gene_expression_renamed.csv")
df_test= df_test1
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)

LR Training Accuracy: 93.63%
LR Testing Accuracy: 96.91%
Precision: 0.97, Recall: 0.97, F1-Score: 0.97, MCC: 0.94
LR Testing Accuracy: 96.91%
Confusion Matrix:
[[114   3]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.96      0.96      0.96        77

    accuracy                           0.97       194
   macro avg       0.97      0.97      0.97       194
weighted avg       0.97      0.97      0.97       194

------------------------------------------------------------
KNN Training Accuracy: 93.61%
KNN Testing Accuracy: 96.39%
Precision: 0.96, Recall: 0.96, F1-Score: 0.96, MCC: 0.92
KNN Testing Accuracy: 96.39%
Confusion Matrix:
[[113   4]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.95      0.96      0.95        77

    accuracy                     

## Top 40 Hub Genes

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['PRNP', 'EHD2', 'GABARAPL1', 'CORO1C', 'DPT', 'SNCA', 'TMEM47', 'LAMB2',
                       'TIMP2', 'JAM3', 'MEF2C', 'FNBP1', 'RHOB', 'PRKD1', 'FLNA', 'TGFB1I1',
                       'RHOQ', 'CAV2', 'PPP3CB', 'PTRF', 'ITPR1', 'PALLD', 'CSRP1', 'TNS1',
                       'ILK', 'ACTN1', 'SPARCL1', 'RASL12', 'DPYSL3', 'TUBB', 'SLIT2', 'EMILIN1''target']

df_train = train_main
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE106582_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE106582_gene_expression_renamed.csv")
df_test= df_test1
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)

LR Training Accuracy: 93.63%
LR Testing Accuracy: 96.91%
Precision: 0.97, Recall: 0.97, F1-Score: 0.97, MCC: 0.94
LR Testing Accuracy: 96.91%
Confusion Matrix:
[[114   3]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.96      0.96      0.96        77

    accuracy                           0.97       194
   macro avg       0.97      0.97      0.97       194
weighted avg       0.97      0.97      0.97       194

------------------------------------------------------------
KNN Training Accuracy: 93.61%
KNN Testing Accuracy: 96.39%
Precision: 0.96, Recall: 0.96, F1-Score: 0.96, MCC: 0.92
KNN Testing Accuracy: 96.39%
Confusion Matrix:
[[113   4]
 [  3  74]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       117
           1       0.95      0.96      0.95        77

    accuracy                     

# 2nd Dataset [GSE21815]

## Top 10 Gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE21815_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE21815_gene_expression_renamed.csv")
df_test= df_test2
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 59.98%
LR Testing Accuracy: 93.62%
Precision: 0.88, Recall: 0.94, F1-Score: 0.91, MCC: 0.00
LR Testing Accuracy: 93.62%
Confusion Matrix:
[[  0   9]
 [  0 132]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.94      1.00      0.97       132

    accuracy                           0.94       141
   macro avg       0.47      0.50      0.48       141
weighted avg       0.88      0.94      0.91       141

------------------------------------------------------------
KNN Training Accuracy: 71.59%
KNN Testing Accuracy: 81.56%
Precision: 0.89, Recall: 0.82, F1-Score: 0.85, MCC: 0.05
KNN Testing Accuracy: 81.56%
Confusion Matrix:
[[  2   7]
 [ 19 113]]
Classification Report:
              precision    recall  f1-score   support

           0       0.10      0.22      0.13         9
           1       0.94      0.86      0.90       132

    accuracy                     

## Top 20 Gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','DPYSL3','TIMP2',
                       'PRNP', 'SPARCL1', 'SNCA', 'CSRP1', 'ILK', 'MEF2C', 'PALLD', 'CAV2','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE21815_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE21815_gene_expression_renamed.csv")
df_test= df_test2
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 86.08%
LR Testing Accuracy: 83.69%
Precision: 0.94, Recall: 0.84, F1-Score: 0.87, MCC: 0.38
LR Testing Accuracy: 83.69%
Confusion Matrix:
[[  7   2]
 [ 21 111]]
Classification Report:
              precision    recall  f1-score   support

           0       0.25      0.78      0.38         9
           1       0.98      0.84      0.91       132

    accuracy                           0.84       141
   macro avg       0.62      0.81      0.64       141
weighted avg       0.94      0.84      0.87       141

------------------------------------------------------------
KNN Training Accuracy: 81.38%
KNN Testing Accuracy: 72.34%
Precision: 0.91, Recall: 0.72, F1-Score: 0.79, MCC: 0.16
KNN Testing Accuracy: 72.34%
Confusion Matrix:
[[ 5  4]
 [35 97]]
Classification Report:
              precision    recall  f1-score   support

           0       0.12      0.56      0.20         9
           1       0.96      0.73      0.83       132

    accuracy                         

## Top 40 gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['PRNP', 'EHD2', 'GABARAPL1', 'CORO1C', 'DPT', 'SNCA', 'TMEM47', 'LAMB2',
                       'TIMP2', 'JAM3', 'MEF2C', 'FNBP1', 'RHOB', 'PRKD1', 'FLNA', 'TGFB1I1',
                       'RHOQ', 'CAV2', 'PPP3CB', 'PTRF', 'ITPR1', 'PALLD', 'CSRP1', 'TNS1',
                       'ILK', 'ACTN1', 'SPARCL1', 'RASL12', 'DPYSL3', 'TUBB', 'SLIT2', 'EMILIN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE21815_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE21815_gene_expression_renamed.csv")
df_test= df_test2
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 93.36%
LR Testing Accuracy: 95.04%
Precision: 0.94, Recall: 0.95, F1-Score: 0.94, MCC: 0.48
LR Testing Accuracy: 95.04%
Confusion Matrix:
[[  3   6]
 [  1 131]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.33      0.46         9
           1       0.96      0.99      0.97       132

    accuracy                           0.95       141
   macro avg       0.85      0.66      0.72       141
weighted avg       0.94      0.95      0.94       141

------------------------------------------------------------
KNN Training Accuracy: 86.35%
KNN Testing Accuracy: 76.60%
Precision: 0.90, Recall: 0.77, F1-Score: 0.82, MCC: 0.14
KNN Testing Accuracy: 76.60%
Confusion Matrix:
[[  4   5]
 [ 28 104]]
Classification Report:
              precision    recall  f1-score   support

           0       0.12      0.44      0.20         9
           1       0.95      0.79      0.86       132

    accuracy                     

# 3rd Dataset [GSE8671]

## Top 10 gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE8671_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE8671_gene_expression_renamed.csv")
df_test= df_test3
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 59.98%
LR Testing Accuracy: 79.69%
Precision: 0.86, Recall: 0.80, F1-Score: 0.79, MCC: 0.65
LR Testing Accuracy: 79.69%
Confusion Matrix:
[[19 13]
 [ 0 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.59      0.75        32
           1       0.71      1.00      0.83        32

    accuracy                           0.80        64
   macro avg       0.86      0.80      0.79        64
weighted avg       0.86      0.80      0.79        64

------------------------------------------------------------
KNN Training Accuracy: 71.59%
KNN Testing Accuracy: 90.62%
Precision: 0.92, Recall: 0.91, F1-Score: 0.91, MCC: 0.83
KNN Testing Accuracy: 90.62%
Confusion Matrix:
[[32  0]
 [ 6 26]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      1.00      0.91        32
           1       1.00      0.81      0.90        32

    accuracy                           0.

## Top 20 gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','DPYSL3','TIMP2',
                       'PRNP', 'SPARCL1', 'SNCA', 'CSRP1', 'ILK', 'MEF2C', 'PALLD', 'CAV2','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE8671_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE8671_gene_expression_renamed.csv")
df_test= df_test3
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 86.08%
LR Testing Accuracy: 90.62%
Precision: 0.92, Recall: 0.91, F1-Score: 0.91, MCC: 0.83
LR Testing Accuracy: 90.62%
Confusion Matrix:
[[26  6]
 [ 0 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.84      1.00      0.91        32

    accuracy                           0.91        64
   macro avg       0.92      0.91      0.91        64
weighted avg       0.92      0.91      0.91        64

------------------------------------------------------------
KNN Training Accuracy: 81.38%
KNN Testing Accuracy: 82.81%
Precision: 0.87, Recall: 0.83, F1-Score: 0.82, MCC: 0.70
KNN Testing Accuracy: 82.81%
Confusion Matrix:
[[32  0]
 [11 21]]
Classification Report:
              precision    recall  f1-score   support

           0       0.74      1.00      0.85        32
           1       1.00      0.66      0.79        32

    accuracy                           0.

## Top 40 gene

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['PRNP', 'EHD2', 'GABARAPL1', 'CORO1C', 'DPT', 'SNCA', 'TMEM47', 'LAMB2',
                       'TIMP2', 'JAM3', 'MEF2C', 'FNBP1', 'RHOB', 'PRKD1', 'FLNA', 'TGFB1I1',
                       'RHOQ', 'CAV2', 'PPP3CB', 'PTRF', 'ITPR1', 'PALLD', 'CSRP1', 'TNS1',
                       'ILK', 'ACTN1', 'SPARCL1', 'RASL12', 'DPYSL3', 'TUBB', 'SLIT2', 'EMILIN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE8671_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE8671_gene_expression_renamed.csv")
df_test= df_test3
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 93.36%
LR Testing Accuracy: 100.00%
Precision: 1.00, Recall: 1.00, F1-Score: 1.00, MCC: 1.00
LR Testing Accuracy: 100.00%
Confusion Matrix:
[[32  0]
 [ 0 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        32

    accuracy                           1.00        64
   macro avg       1.00      1.00      1.00        64
weighted avg       1.00      1.00      1.00        64

------------------------------------------------------------
KNN Training Accuracy: 86.35%
KNN Testing Accuracy: 95.31%
Precision: 0.96, Recall: 0.95, F1-Score: 0.95, MCC: 0.91
KNN Testing Accuracy: 95.31%
Confusion Matrix:
[[29  3]
 [ 0 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        32
           1       0.91      1.00      0.96        32

    accuracy                           

# 4th Dataset GSE44076

## Top 10 genes

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE44076_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE44076_gene_expression_renamed.csv")
df_test= df_test3
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 59.98%
LR Testing Accuracy: 79.69%
Precision: 0.86, Recall: 0.80, F1-Score: 0.79, MCC: 0.65
LR Testing Accuracy: 79.69%
Confusion Matrix:
[[19 13]
 [ 0 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.59      0.75        32
           1       0.71      1.00      0.83        32

    accuracy                           0.80        64
   macro avg       0.86      0.80      0.79        64
weighted avg       0.86      0.80      0.79        64

------------------------------------------------------------
KNN Training Accuracy: 71.59%
KNN Testing Accuracy: 90.62%
Precision: 0.92, Recall: 0.91, F1-Score: 0.91, MCC: 0.83
KNN Testing Accuracy: 90.62%
Confusion Matrix:
[[32  0]
 [ 6 26]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      1.00      0.91        32
           1       1.00      0.81      0.90        32

    accuracy                           0.

## Top 20 genes

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['FLNA', 'TNS1','RHOQ','PTRF','TGFB1I1', 'RHOB', 'ACTN1','DPYSL3','TIMP2',
                       'PRNP', 'SPARCL1', 'SNCA', 'CSRP1', 'ILK', 'MEF2C', 'PALLD', 'CAV2','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE44076_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE44076_gene_expression_renamed.csv")
df_test= df_test4
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 86.08%
LR Testing Accuracy: 91.89%
Precision: 0.92, Recall: 0.92, F1-Score: 0.92, MCC: 0.82
LR Testing Accuracy: 91.89%
Confusion Matrix:
[[39 11]
 [ 1 97]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.78      0.87        50
           1       0.90      0.99      0.94        98

    accuracy                           0.92       148
   macro avg       0.94      0.88      0.90       148
weighted avg       0.92      0.92      0.92       148

------------------------------------------------------------
KNN Training Accuracy: 81.38%
KNN Testing Accuracy: 60.14%
Precision: 0.55, Recall: 0.60, F1-Score: 0.56, MCC: -0.00
KNN Testing Accuracy: 60.14%
Confusion Matrix:
[[ 9 41]
 [18 80]]
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.18      0.23        50
           1       0.66      0.82      0.73        98

    accuracy                           0

## Top 40 genes

In [ ]:
#path = "ML_DEG_dataset.csv"
#df_train = pd.read_csv("ML_DEG_dataset.csv")
columns_of_interest = ['PRNP', 'EHD2', 'GABARAPL1', 'CORO1C', 'DPT', 'SNCA', 'TMEM47', 'LAMB2',
                       'TIMP2', 'JAM3', 'MEF2C', 'FNBP1', 'RHOB', 'PRKD1', 'FLNA', 'TGFB1I1',
                       'RHOQ', 'CAV2', 'PPP3CB', 'PTRF', 'ITPR1', 'PALLD', 'CSRP1', 'TNS1',
                       'ILK', 'ACTN1', 'SPARCL1', 'RASL12', 'DPYSL3', 'TUBB', 'SLIT2', 'EMILIN1','target']

df_train= train_main
df_train = df_train[columns_of_interest]
df_train = df_train.iloc[:, 1:]
df_train = df_train[[col for col in df_train.columns if col != 'target'] + ['target']]
X_train = df_train.iloc[:, 0:-1]
y_train = df_train.iloc[:, -1]

#path = "GSE44076_gene_expression_renamed.csv"
#df_test = pd.read_csv("GSE44076_gene_expression_renamed.csv")
df_test= df_test4
df_test = df_test.iloc[:, 1:]
df_test = df_test[[col for col in df_test.columns if col != 'target'] + ['target']]

X_test = df_test.iloc[:, 0:-1]
y_test = df_test.iloc[:, -1]

common_cols = set(X_train.columns).intersection(X_test.columns)
X_train_common = X_train[list(common_cols)]
X_test_common = X_test[list(common_cols)]


# Validation dataset
validation_size = 0.30
seed = 7

# Define base models
models = {
    'LR': LogisticRegression(max_iter=1000),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Bagging': BaggingClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'XGBoost':XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Evaluate models
for name, model in models.items():
    kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
    cv_results = cross_val_score(model, X_train_common, y_train, cv=kfold, scoring='accuracy')
    print(f"{name} Training Accuracy: {cv_results.mean() * 100:.2f}%")

    # Train and test each model
    model.fit(X_train_common, y_train)
    predictions = model.predict(X_test_common)
    # Calculate metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
    recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
    f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)
    mcc = matthews_corrcoef(y_test, predictions)

    # Print results
    print(f"{name} Testing Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}, MCC: {mcc:.2f}")
    test_accuracy = accuracy_score(y_test, predictions)
    print(f"{name} Testing Accuracy: {test_accuracy * 100:.2f}%")

    # Print confusion matrix and classification report
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("Classification Report:")
    print(classification_report(y_test, predictions))
    print("-" * 60)


LR Training Accuracy: 93.36%
LR Testing Accuracy: 66.22%
Precision: 0.44, Recall: 0.66, F1-Score: 0.53, MCC: 0.00
LR Testing Accuracy: 66.22%
Confusion Matrix:
[[ 0 50]
 [ 0 98]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.66      1.00      0.80        98

    accuracy                           0.66       148
   macro avg       0.33      0.50      0.40       148
weighted avg       0.44      0.66      0.53       148

------------------------------------------------------------
KNN Training Accuracy: 86.35%
KNN Testing Accuracy: 66.22%
Precision: 0.44, Recall: 0.66, F1-Score: 0.53, MCC: 0.00
KNN Testing Accuracy: 66.22%
Confusion Matrix:
[[ 0 50]
 [ 0 98]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.66      1.00      0.80        98

    accuracy                           0.